name: Release to Che Plugin Registry

on:
  push:
    tags:
      - '*'

jobs:
  chePluginRegistryUpdate:
    runs-on: ubuntu-latest
    steps:
      # Checkout this extension
      - uses: actions/checkout@v2

      # Checkout the plugin registry
      - uses: actions/checkout@v2
        with:
          repository: jpinkney/che-plugin-registry
          path: che-plugin-registry
      
      # Create the new meta.yaml, update the latest.txt and vscode-extensions.json
      - uses: jpinkney/che-plugin-updater@v1
        id: che-plugin-updater
        with:
          pluginPath: redhat/vscode-yaml
      
      # Create a pull request to the che plugin registry
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          path: che-plugin-registry
          token: ${{ secrets.PAT }}
          committer: Josh Pinkney <jpinkney@gmail.com>
          commit-message: Update ${{ steps.che-plugin-updater.outputs.name }} to ${{ steps.che-plugin-updater.outputs.version }}
          signoff: true
          base: master
          branch: ${{ steps.che-plugin-updater.outputs.name }}-${{ steps.che-plugin-updater.outputs.version }}-update
          delete-branch: true
          title: Update ${{ steps.che-plugin-updater.outputs.name }} to ${{ steps.che-plugin-updater.outputs.version }}
          labels: |
            untested
          body: |
            ### What does this PR do?
            This PR updates ${{ steps.che-plugin-updater.outputs.name }} to version ${{ steps.che-plugin-updater.outputs.version }}
            
            ### Screenshot/screencast of this PR
            ### What issues does this PR fix or reference?
            ### How to test this PR?
            ### PR Checklist
            [As the author of this Pull Request I made sure that:](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#pull-request-template-and-its-checklist)
            - [ ] [The Eclipse Contributor Agreement is valid](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#the-eclipse-contributor-agreement-is-valid)
            - [ ] [Code produced is complete](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#code-produced-is-complete)
            - [ ] [Code builds without errors](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#code-builds-without-errors)
            - [ ] [Tests are covering the bugfix](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#tests-are-covering-the-bugfix)
            - [ ] [The repository devfile is up to date and works](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#the-repository-devfile-is-up-to-date-and-works)
            - [ ] [Sections `What issues does this PR fix or reference` and `How to test this PR` completed](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#sections-what-issues-does-this-pr-fix-or-reference-and-how-to-test-this-pr-completed)
            - [ ] [Relevant user documentation updated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#relevant-contributing-documentation-updated)
            - [ ] [Relevant contributing documentation updated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#relevant-contributing-documentation-updated)
            - [ ] [CI/CD changes implemented, documented and communicated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#cicd-changes-implemented-documented-and-communicated)
            ### Reviewers
            Reviewers, please comment how you tested the PR when approving it.